data:
  mysql:
    host: localhost
    port: 3308
    database: web
    username: root
    password: jscomet_@_21232
  redis:
    host: localhost
    port: 6381
    password: jscomet_@_21232

app:
  domain: http://localhost
  front:
    url: ${app.domain}/#
    index-url: ${app.front.url}
    error-url: ${app.front.url}?login_failed=1
  back:
    url: localhost:8080
    upload-path: ./uploads